name: Build Test
on: [push]

jobs:
  listify-auto:
    runs-on: ubuntu-latest
    name: listify auto
    steps:
    - name: listify action step
      uses: ./
      with:
        listify: ./ --blog
        github_token: ${{ secrets.GH_TOKEN }}
